### ISSUE TITLE
Pretrained weight not available

### ISSUE THREAD

**Issue by Youyi7** [lochenchou/DORN#2]
Hello, your implemention for Dorn on pytorch is very useful. While I can't train it, could you please provide the weight of your resnet?

The location of your code is in: DORN/model/resnet.py line:123
`        if pretrained:
            saved_state_dict = torch.load('/datasets/KITTI/depth_prediction/pretrained/resnet101-imagenet.pth',
                                          map_location="cpu")`

Without this weight, the performance may not good, thanks very much.

**Comment by lochenchou** [comment]
Hi,
You could download the pretrained weight from the link below
http://sceneparsing.csail.mit.edu/model/pretrained_resnet/
